# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-01 05:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historyofcg', '0002_initial_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='type',
            field=models.CharField(choices=[('UP', 'up'), ('DOWN', 'down')], max_length=4),
        ),
    ]
