version: '3'
services:
  webserver:
    container_name: hocg-webserver
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    volumes: 
      - ".:/usr/src/app"
    command: python manage.py runserver 0.0.0.0:8000 --settings=settings.development

  postgres:
    container_name: hocg-postgres
    image: postgres:10.1
    expose:
      - 5432
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'development'
      POSTGRES_DB: 'hocg'
    volumes:
      - data:/var/lib/postgresql/data


volumes:
  data: {}
